import './globals.css'
import { Inter } from 'next/font/google'
import styles from './page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" />
      </head>
      <body className={styles.container}>

        <nav className={styles.navMenu}>
          {/* <img class={styles.logo} src="https://img.freepik.com/premium-vector/duck-king-mascot-logo-design-illustration-vector-isolated-dark-background_268458-729.jpg?w=2000" alt="" width={180} height={137} /> */}
          <h2 className={styles.title}>Squad Builder</h2>
          <div className={styles.overlay}>
          </div>
        </nav>
        {children}
      </body>
    </html >
  )
}
